### ISSUE TITLE
P font sizing should be 18px

### ISSUE THREAD

**Issue by benjskim** [apicaldesign/apicaldesign.github.io#13]
Currently, it's at 16px.

A few of the request I've made have it at 18px, so I don't know why it hasn't been changed.

Some UX Designers in my network called me out saying they had to squint to read our text.

**Comment by nadia39** [comment]
I can work on this!

**Comment by nadia39** [comment]
It seems to already be 18px..
Do you mean body font size?

**Comment by benjskim** [comment]
The font size in the bulleted lists has to change to 18px as well.
