### ISSUE TITLE
New Hero Image for /training.html

### ISSUE THREAD

**Issue by benjskim** [apicaldesign/apicaldesign.github.io#55]
Replace current hero image with this file:

![img_20170522_111740](https://cloud.githubusercontent.com/assets/4932055/26620377/29983cae-4615-11e7-81fa-1b6c82b76689.jpg)

**Comment by tjmonsi** [comment]
@benjskim can you give it to rocky to change the colors? I don't have any photoshop with me

**Comment by jelvin** [comment]
Issue for review in `/staging`

**Comment by benjskim** [comment]
Looks good! Let me know when it's in production and I'll close this issue.

**Comment by benjskim** [comment]
Bumping this @jelvin @tjmonsi

**Comment by tjmonsi** [comment]
Hi @benjskim will do this, this afternoon.

**Comment by tjmonsi** [comment]
@benjskim this is done in production
