### ISSUE TITLE
Country Flags not efficient in mobile

### ISSUE THREAD

**Issue by benjskim** [apicaldesign/apicaldesign.github.io#56]
This is on /training.html. See the attached photos
<img width="1015" alt="screen shot 2017-05-31 at 3 26 45 pm" src="https://cloud.githubusercontent.com/assets/4932055/26620464/9342f63a-4615-11e7-910b-688675430b3a.png">
<img width="1019" alt="screen shot 2017-05-31 at 3 26 49 pm" src="https://cloud.githubusercontent.com/assets/4932055/26620465/9346d32c-4615-11e7-8a2c-c5f36c2e1b65.png">

**Comment by tjmonsi** [comment]
Is this what's happening on ios 9?
