### ISSUE TITLE
Our logo is not being rendered properly in some browsers

### ISSUE THREAD

**Issue by benjskim** [apicaldesign/apicaldesign.github.io#57]
Ask Rocky about details, but our logo should look like this:
<img width="507" alt="screen shot 2017-05-26 at 7 10 11 pm" src="https://cloud.githubusercontent.com/assets/4932055/26620518/bdf0f7d8-4615-11e7-9924-7b291c9aaed7.png">

But on his screen, it shows up like this:
![doesn t render font](https://cloud.githubusercontent.com/assets/4932055/26620583/fc02227c-4615-11e7-834f-a596880cef08.jpg)

**Comment by tjmonsi** [comment]
Yeah this is a problem of using SVG as logo rather than text. I'll look for a way

**Comment by tjmonsi** [comment]
Please check if fixed

**Comment by jelvin** [comment]
Issue for review in `/staging`

**Comment by benjskim** [comment]
working fine no, please move to production

**Comment by benjskim** [comment]
Bumping this @jelvin @tjmonsi

**Comment by benjskim** [comment]
THIS IS ON PRODUCTION. PLEASE FIX ASAP. @tjmonsi 
<img width="775" alt="screen shot 2017-06-12 at 2 30 42 pm" src="https://user-images.githubusercontent.com/4932055/27056128-c4ec8006-4f7b-11e7-9601-c85a6256bae5.png">

**Comment by jelvin** [comment]
Issue resolved. I've updated the header
