### ISSUE TITLE
Border-radius on all browsers

### ISSUE THREAD

**Issue by benjskim** [apicaldesign/apicaldesign.github.io#58]
All of our buttons and text fields should have the border radius of 0 on all views and platforms.

It seems like we're not doing that (given to me by a friend):
<img width="293" alt="screen shot 2017-05-31 at 3 34 01 pm" src="https://cloud.githubusercontent.com/assets/4932055/26620645/34a65d3c-4616-11e7-94af-bb17d3f35944.png">

**Comment by tjmonsi** [comment]
@benjskim would like to know his browser so I can test it further

**Comment by benjskim** [comment]
@tjmonsi All I know, she's using an iPhone, so it's either Safari or Chrome.

**Comment by tjmonsi** [comment]
I'll check it out on Safari here.

**Comment by benjskim** [comment]
I think it was Chrome on iPhone. Safari has a different UI on iPhone
