### ISSUE TITLE
Styleguide is down

### ISSUE THREAD

**Issue by benjskim** [apicaldesign/apicaldesign.github.io#60]
<img width="1274" alt="screen shot 2017-06-01 at 7 40 23 pm" src="https://cloud.githubusercontent.com/assets/4932055/26678154/b9f56136-4701-11e7-91cf-f6f15f210dc8.png">

**Comment by tjmonsi** [comment]
I made a commit directly to master. The thing is it is supposed to be /styleguide/dist

see https://www.apicaldesign.com/styleguide/dist/

**Comment by tjmonsi** [comment]
Please close if fixed :)
