### ISSUE TITLE
Text in SVG not rendering properly

### ISSUE THREAD

**Issue by benjskim** [apicaldesign/apicaldesign.github.io#64]
We'll have to recreate this on Sketch, stay tuned. I think this is also related to our Logo Problem too

![image](https://cloud.githubusercontent.com/assets/4932055/26732262/8d548790-47e9-11e7-86ce-0d44b1add64d.png)

**Comment by tjmonsi** [comment]
Yes. But that would be Jelvin's work or Rock's work. In any case, i think i
fixed it already? Can you check?

**Comment by jelvin** [comment]
I'll push the latest version once I have steady internet. can't push anything currently :\ I've updated the SVG's and turned it into shapes. The artist forgot to change the text into shapes :P

**Comment by jelvin** [comment]
Issue for review in `/staging`

**Comment by benjskim** [comment]
This is how it looks for me on `/staging `
<img width="1127" alt="screen shot 2017-06-04 at 11 45 06 am" src="https://cloud.githubusercontent.com/assets/4932055/26758762/b8489ee6-491a-11e7-99e0-4bd74420a153.png">

**Comment by benjskim** [comment]
Bumping this @jelvin, @tjmonsi

**Comment by benjskim** [comment]
This is on production, please fix ASAP @tjmonsi 
<img width="1195" alt="screen shot 2017-06-12 at 2 28 09 pm" src="https://user-images.githubusercontent.com/4932055/27056192-f78472c6-4f7b-11e7-82d0-154dc9eb7283.png">

**Comment by tjmonsi** [comment]
Hi @benjskim will do this, this afternoon.
