### ISSUE TITLE
Change hero image on /solutions

### ISSUE THREAD

**Issue by benjskim** [apicaldesign/apicaldesign.github.io#72]
To this photo:
![20160902_184910](https://user-images.githubusercontent.com/4932055/27056917-d6bf018e-4f7e-11e7-9ed2-d68ef0b9dfb2.jpg)

**Comment by tjmonsi** [comment]
@benjskim Do we have someone who can change the image colors? I don't have photoshop with me as of now :(

**Comment by benjskim** [comment]
Fixed #72
